[project]
name = 'Supply-Chain-Financing'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.financing-marketplace]
path = 'contracts/financing-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.invoice-tokenization]
path = 'contracts/invoice-tokenization.clar'
clarity_version = 2
epoch = 2.5

[contracts.repayment-tracking]
path = 'contracts/repayment-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
